# version: "3.4"

services:
  postgres:
    container_name: appointment_data
    image: postgres
    ports:
      - 5430:5432
    volumes:
      - postgres_data_as:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: appointment
      POSTGRES_PASSWORD: admin

volumes:
  postgres_data_as: